-- Create Employee table

CREATE TABLE "Employees" (
    "EmployeeID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "LastName" NVARCHAR2(20) NOT NULL,
    "FirstName" NVARCHAR2(10) NOT NULL,
    "Title" NVARCHAR2(30),
    "TitleOfCourtesy" NVARCHAR2(25),
    "BirthDate" DATE,
    "HireDate" DATE,
    "Address" NVARCHAR2(60),
    "City" NVARCHAR2(15),
    "Region" NVARCHAR2(15),
    "PostalCode" NVARCHAR2(10),
    "Country" NVARCHAR2(15),
    "HomePhone" NVARCHAR2(24),
    "Extension" NVARCHAR2(4),
    "Photo" BLOB,
    "Notes" NCLOB,
    "ReportsTo" NUMBER,
    "PhotoPath" NVARCHAR2(255)
) TABLESPACE tbs_northwind;

ALTER TABLE "Employees" ADD CONSTRAINT "PK_Employees"  PRIMARY KEY ("EmployeeID");
ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_Employees"  FOREIGN KEY ("ReportsTo") REFERENCES "Employees"("EmployeeID");

CREATE  INDEX "LastName" ON "Employees"("LastName");
CREATE  INDEX "PostalCodeEmployee" ON "Employees"("PostalCode");

CREATE OR REPLACE TRIGGER CK_Birthdate_TRG 
BEFORE INSERT OR UPDATE ON "Employees" 
FOR EACH ROW 
BEGIN 
	IF : NEW."BirthDate" >= SYSDATE THEN 
		RAISE_APPLICATION_ERROR(-20001, 'Birthdate must be before the current date.');
	END IF;
END;
/

-- Create Categories table

CREATE TABLE "Categories" (
	"CategoryID" NUMBER GENERATED BY DEFAULT AS IDENTITY ,
	"CategoryName" NVARCHAR2(15) NOT NULL ,
	"Description" NCLOB ,
	"Picture" BLOB
) TABLESPACE tbs_northwind;

ALTER TABLE "Categories" ADD CONSTRAINT "PK_Categories"  PRIMARY KEY ("CategoryID");

CREATE  INDEX "CategoryName" ON "Categories"("CategoryName");

-- Create Customer table

CREATE TABLE "Customers" (
	"CustomerID" NCHAR (5) NOT NULL ,
	"CompanyName" NVARCHAR2 (40) NOT NULL ,
	"ContactName" NVARCHAR2 (30) ,
	"ContactTitle" NVARCHAR2 (30) ,
	"Address" NVARCHAR2 (60) ,
	"City" NVARCHAR2 (15) ,
	"Region" NVARCHAR2 (15) ,
	"PostalCode" NVARCHAR2 (10)  ,
	"Country" NVARCHAR2 (15) ,
	"Phone" NVARCHAR2 (24) ,
	"Fax" NVARCHAR2 (24) 
) TABLESPACE tbs_northwind;

ALTER TABLE "Customers" ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerID");

CREATE  INDEX "City" ON "Customers"("City");
CREATE  INDEX "CompanyNameCustomer" ON "Customers"("CompanyName");
CREATE  INDEX "PostalCodeCustomer" ON "Customers"("PostalCode");
CREATE  INDEX "Region" ON "Customers"("Region");

-- Create Shippers table

CREATE TABLE "Shippers" (
	"ShipperID" NUMBER GENERATED BY DEFAULT AS IDENTITY ,
	"CompanyName" NVARCHAR2 (40) NOT NULL ,
	"Phone" NVARCHAR2 (24)
) TABLESPACE tbs_northwind;

ALTER TABLE "Shippers" ADD CONSTRAINT "PK_Shippers" PRIMARY KEY ("ShipperID");


-- Create Suppliers table

CREATE TABLE "Suppliers" (
	"SupplierID" NUMBER GENERATED BY DEFAULT AS IDENTITY ,
	"CompanyName" NVARCHAR2 (40) NOT NULL ,
	"ContactName" NVARCHAR2 (30) ,
	"ContactTitle" NVARCHAR2 (30) ,
	"Address" NVARCHAR2 (60) ,
	"City" NVARCHAR2 (15) ,
	"Region" NVARCHAR2 (15) ,
	"PostalCode" NVARCHAR2 (10) ,
	"Country" NVARCHAR2 (15) ,
	"Phone" NVARCHAR2 (24) ,
	"Fax" NVARCHAR2 (24) ,
	"HomePage" NCLOB 
) TABLESPACE tbs_northwind;

ALTER TABLE "Suppliers" ADD CONSTRAINT "PK_Suppliers" PRIMARY KEY ("SupplierID");

CREATE  INDEX "CompanyNameSupplier" ON "Suppliers"("CompanyName");
CREATE  INDEX "PostalCodeSupplier" ON "Suppliers"("PostalCode");

-- Create Orders table

CREATE TABLE "Orders" (
	"OrderID" NUMBER GENERATED BY DEFAULT AS IDENTITY ,
	"CustomerID" NCHAR (5) ,
	"EmployeeID" NUMBER ,
	"OrderDate" DATE ,
	"RequiredDate" DATE ,
	"ShippedDate" DATE ,
	"ShipVia" NUMBER ,
	"Freight" NUMBER(12,4) DEFAULT 0,
	"ShipName" NVARCHAR2 (40) ,
	"ShipAddress" NVARCHAR2 (60) ,
	"ShipCity" NVARCHAR2 (15) ,
	"ShipRegion" NVARCHAR2 (15) ,
	"ShipPostalCode" NVARCHAR2 (10) ,
	"ShipCountry" NVARCHAR2 (15)
) TABLESPACE tbs_northwind;

ALTER TABLE "Orders" ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderID");
ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Customers" FOREIGN KEY ("CustomerID") REFERENCES "Customers"("CustomerID");
ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Employees" FOREIGN KEY ("EmployeeID") REFERENCES "Employees"("EmployeeID");
ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Shippers" FOREIGN KEY ("ShipVia") REFERENCES "Shippers"("ShipperID");

CREATE  INDEX "CustomerID" ON "Orders"("CustomerID");
CREATE  INDEX "CustomersOrders" ON "Orders"("CustomerID");
CREATE  INDEX "EmployeeID" ON "Orders"("EmployeeID");
CREATE  INDEX "EmployeesOrders" ON "Orders"("EmployeeID");
CREATE  INDEX "OrderDate" ON "Orders"("OrderDate");
CREATE  INDEX "ShippedDate" ON "Orders"("ShippedDate");
CREATE  INDEX "ShippersOrders" ON "Orders"("ShipVia");
CREATE  INDEX "ShipPostalCode" ON "Orders"("ShipPostalCode");

-- Create Products table

CREATE TABLE "Products" (
	"ProductID" NUMBER GENERATED BY DEFAULT AS IDENTITY ,
	"ProductName" NVARCHAR2 (40) NOT NULL ,
	"SupplierID" NUMBER ,
	"CategoryID" NUMBER ,
	"QuantityPerUnit" NVARCHAR2 (20) ,
	"UnitPrice" NUMBER(12,2) DEFAULT 0,
	"UnitsInStock" NUMBER(5) DEFAULT 0,
	"UnitsOnOrder" NUMBER(5) DEFAULT 0,
	"ReorderLevel" NUMBER(5) DEFAULT 0,
	"Discontinued" NUMBER(1) DEFAULT 0
) TABLESPACE tbs_northwind;

ALTER TABLE "Products" ADD CONSTRAINT "PK_Products" PRIMARY KEY ("ProductID");
ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Categories" FOREIGN KEY ("CategoryID") REFERENCES "Categories" ("CategoryID");
ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Suppliers" FOREIGN KEY ("SupplierID") REFERENCES "Suppliers" ("SupplierID");
ALTER TABLE "Products" ADD CONSTRAINT "CK_Products_UnitPrice" CHECK ("UnitPrice" >= 0);
ALTER TABLE "Products" ADD CONSTRAINT "CK_ReorderLevel" CHECK ("ReorderLevel" >= 0);
ALTER TABLE "Products" ADD CONSTRAINT "CK_UnitsInStock" CHECK ("UnitsInStock" >= 0);
ALTER TABLE "Products" ADD CONSTRAINT "CK_UnitsOnOrder" CHECK ("UnitsOnOrder" >= 0);

CREATE  INDEX "CategoryID" ON "Products"("CategoryID");
CREATE  INDEX "ProductName" ON "Products"("ProductName");
CREATE  INDEX "SupplierID" ON "Products"("SupplierID");

-- Create orderDetails table

CREATE TABLE "Order_Details" (
	"OrderID" NUMBER NOT NULL ,
	"ProductID" NUMBER NOT NULL ,
	"UnitPrice" NUMBER(12,2) DEFAULT 0,
	"Quantity" NUMBER(5) DEFAULT 1,
	"Discount" FLOAT DEFAULT 0
) TABLESPACE tbs_northwind;

ALTER TABLE "Order_Details" ADD CONSTRAINT "PK_Order_Details" PRIMARY KEY ("OrderID", "ProductID");
ALTER TABLE "Order_Details" ADD CONSTRAINT "FK_Order_Details_Orders" FOREIGN KEY ("OrderID") REFERENCES "Orders" ("OrderID");
ALTER TABLE "Order_Details" ADD CONSTRAINT "FK_Order_Details_Products" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ProductID");
ALTER TABLE "Order_Details" ADD CONSTRAINT "CK_Discount" CHECK ("Discount" >= 0 and ("Discount" <= 1));
ALTER TABLE "Order_Details" ADD CONSTRAINT "CK_Quantity" CHECK ("Quantity" > 0);
ALTER TABLE "Order_Details" ADD CONSTRAINT "CK_UnitPrice" CHECK ("UnitPrice" >= 0);


CREATE  INDEX "OrderID" ON "Order_Details"("OrderID");
CREATE  INDEX "OrdersOrder_Details" ON "Order_Details"("OrderID");
CREATE  INDEX "ProductID" ON "Order_Details"("ProductID");
CREATE  INDEX "ProductsOrder_Details" ON "Order_Details"("ProductID");