DROP TABLE "Employees" CASCADE CONSTRAINTS PURGE;
DROP TABLE "Customers" CASCADE CONSTRAINTS PURGE;
DROP TABLE "Shippers" CASCADE CONSTRAINTS PURGE;
DROP TABLE "Orders" CASCADE CONSTRAINTS PURGE;
DROP TABLE "Products" CASCADE CONSTRAINTS PURGE;
DROP TABLE "Categories" CASCADE CONSTRAINTS PURGE;
DROP TABLE "Suppliers" CASCADE CONSTRAINTS PURGE;